<?php

namespace ch\metanet\cms\common;

/**
 * A CMS module response each controller method of a module controller (whether frontend or backend) should return.
 * This object gets generated by calling the CmsModuleController::renderModuleContent method
 * 
 * @see CmsModuleController::renderModuleContent
 * 
 * @author Pascal Muenst <entwicklung@metanet.ch>
 * @copyright Copyright (c) 2014, METANET AG
 */
class CmsModuleResponse
{
	protected $tplFile;
	protected $tplVars;
	protected $httpResponseCode;

	/**
	 * @param string $tplFile
	 * @param array $tplVars
	 * @param int $httpResponseCode
	 */
	public function __construct($tplFile, array $tplVars = array(), $httpResponseCode = 200)
	{
		$this->tplFile = $tplFile;
		$this->tplVars = $tplVars;
		$this->httpResponseCode = $httpResponseCode;
	}

	/**
	 * @return string
	 */
	public function getTplFile()
	{
		return $this->tplFile;
	}
	
	/**
	 * @return array
	 */
	public function getTplVars()
	{
		return $this->tplVars;
	}

	/**
	 * @return int
	 */
	public function getHttpResponseCode()
	{
		return $this->httpResponseCode;
	}
}

/* EOF */